/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbpenyewaan;
import javax.swing.JOptionPane;
import javax.swing.JTable;



/**
 *
 * @author user
 */
public class transaksi extends javax.swing.JFrame {
   String[] Judul={"Nama_Pc","Bayar","Waktu","Tanggal"};
   String[] Field={"Nama_Pc","Bayar","Waktu","Tanggal"};
   String SQL ="SELECT*FROM transaksi";
    int[] Lebar ={100,300,120,80,200,80,100,100};
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        koneksi tugas = new koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
        
        tugas.settingJudulTabel(Tabletransaksi, Judul);
        tugas.tampilTabel(Tabletransaksi, SQL, Judul);
        
        tugas.settingLebarKolom(Tabletransaksi, Lebar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtwaktu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabletransaksi = new javax.swing.JTable();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        txttgl = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Cetak = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setText("Nama pc");

        jLabel2.setText("Bayar");
        jLabel2.setToolTipText("");

        jLabel3.setText("Waktu");

        jLabel4.setText("Tanggal");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        Tabletransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabletransaksi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabletransaksiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tabletransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabletransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabletransaksi);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jLabel5.setText("Rp");

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        Clear.setText("Selesai");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel6.setText("Transaksi");

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txtbayar)
                            .addComponent(txtwaktu)
                            .addComponent(txttgl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edit)
                .addGap(18, 18, 18)
                .addComponent(Cetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kembali)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kembali)
                    .addComponent(Clear)
                    .addComponent(Cetak)
                    .addComponent(Edit)
                    .addComponent(Hapus)
                    .addComponent(Simpan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
 if (txtnama.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Nama_Pc Belum diisi");
 txtnama.requestFocus();
}else if (txtbayar.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Bayar Belum diisi");
 txtbayar.requestFocus();
}else if (txttgl.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Waktu Belum diisi");
 txttgl.requestFocus();
}else if (txtwaktu.getText().trim().equals("")){
 JOptionPane.showMessageDialog(null, "Waktu Belum diisi");
 txtwaktu.requestFocus();
}else if (new koneksi().DuplicateKey("Nama_pc","Nama_pc",txtnama.getText())){
 JOptionPane.showMessageDialog(null, "Nama_pc Sudah Terdaftar");
 txtnama.requestFocus();
}else{
String[] field ={"Nama_pc","Bayar","Waktu","Tanggal"};
String[] isi
={txtnama.getText(),txtbayar.getText(),txtwaktu.getText(),txttgl.getText()};
 new koneksi().SimpanDinamis("transaksi", field, isi);
 new koneksi().settingJudulTabel(Tabletransaksi, Judul);
 new koneksi().tampilTabel(Tabletransaksi, SQL, Judul);
 new koneksi().settingLebarKolom(Tabletransaksi, Lebar);
 
 }
    }//GEN-LAST:event_SimpanActionPerformed

    private void TabletransaksiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabletransaksiAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabletransaksiAncestorAdded

    private void TabletransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabletransaksiMouseClicked
        // TODO add your handling code here:
int row = Tabletransaksi.getSelectedRow();
        txtnama.setText(Tabletransaksi.getModel().getValueAt(row,0).toString());
        txtbayar.setText(Tabletransaksi.getModel().getValueAt(row,1).toString());
        txtwaktu.setText(Tabletransaksi.getModel().getValueAt(row,2).toString());
        txttgl.setText(Tabletransaksi.getModel().getValueAt(row,3).toString());
    }//GEN-LAST:event_TabletransaksiMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
 new koneksi().HapusDinamis("transaksi", "Nama_pc", txtnama.getText());
        JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
        new koneksi().settingJudulTabel(Tabletransaksi, Judul);
        new koneksi().tampilTabel(Tabletransaksi, SQL, Judul);
        new koneksi().settingLebarKolom(Tabletransaksi, Lebar);
        txtnama.setText("");
        txtbayar.setText("");
        txtwaktu.setText("");
        txttgl.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
try {
            String[] field = {"Nama_Pc","Bayar","Waktu","Tanggal"};
            String[] isi = {txtnama.getText(),txtbayar.getText(),txtwaktu.getText(),txttgl.getText()};
            new koneksi().UbahDinamis("transaksi", "Nama_Pc", txtnama.getText(), field, isi);
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            new koneksi().settingJudulTabel(Tabletransaksi, Judul);
            new koneksi().tampilTabel(Tabletransaksi, SQL, Judul);
            new koneksi().settingLebarKolom(Tabletransaksi, Lebar);
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        new koneksi().tampilLaporan("src/laporan/transaksi.jrxml","SELECT*FROM transaksi");
    }//GEN-LAST:event_CetakActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ClearActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
this.hide();
Menu_Utama kembali = new Menu_Utama();
kembali.show();
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabletransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttgl;
    private javax.swing.JTextField txtwaktu;
    // End of variables declaration//GEN-END:variables
}
